name: build

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup
        run: sudo apt-get install -y mingw-w64 libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-mixer-dev
      - name: build
        run: |
          g++ -c src/*.cpp -std=c++14 -O3 -Wall -m64 -I include && mkdir -p bin/release && g++ *.o -o bin/release/main -s -lSDL2main -lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_mixer
      - name: copy resources
        run: |
          cp -vr ./res/ ./bin/release/
      - name: Upload linux Binary
        uses: actions/upload-artifact@v2
        with:
          name: linux
          path: ./bin/release

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64

      - name: Install Dependencies
        run: |
          pacman -Sy --noconfirm mingw-w64-x86_64-toolchain mingw-w64-x86_64-SDL2 mingw-w64-x86_64-SDL2_ttf mingw-w64-x86_64-SDL2_mixer mingw-w64-x86_64-SDL2_image

      - name: Build Project
        run: |
          g++ -c src/*.cpp -std=c++14 -O3 -Wall -m64 -I include -I /mingw64/include
          g++ *.o -o bin/release/main -s -L /mingw64/lib -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_mixer
          start bin/release/main

  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup
        run: sudo apt-get install -y git python3 cmake
      - name: setup emscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk.git && cd emsdk && git pull && ./emsdk install latest && ./emsdk activate latest && source ./emsdk_env.sh && cd ..
      - name: build
        run: |
          source ./emsdk/emsdk_env.sh && emcc src/*.cpp -I include -O2 -s USE_SDL=2 -s USE_SDL_IMAGE=2 -s 'SDL2_IMAGE_FORMATS=["png"]' -s USE_SDL_TTF=2 -s USE_SDL_MIXER=2 --preload-file res -o index.html
      - name: copy files to folder
        run: |
          pwd && ls && mkdir emscripten && cp ./index.data ./emscripten && cp ./index.html ./emscripten && cp ./index.js ./emscripten  && cp ./index.wasm ./emscripten
      - name: Upload linux Binary
        uses: actions/upload-artifact@v2
        with:
          name: emscripten
          path: ./emscripten